/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plane_1: THREE.Mesh;
    Plane_2: THREE.Mesh;
    Circle_1: THREE.Mesh;
    Circle_2: THREE.Mesh;
    Circle_3: THREE.Mesh;
    Plane001_1: THREE.Mesh;
    Plane001_2: THREE.Mesh;
    Plane001_3: THREE.Mesh;
    Plane002: THREE.Mesh;
    Plane003: THREE.Mesh;
    Plane012_1: THREE.Mesh;
    Plane012_2: THREE.Mesh;
    Plane012_3: THREE.Mesh;
    Plane009: THREE.Mesh;
    Plane008: THREE.Mesh;
    Plane005: THREE.Mesh;
    Plane004: THREE.Mesh;
    Plane006: THREE.Mesh;
    Plane007: THREE.Mesh;
    Plane012: THREE.Mesh;
    Text: THREE.Mesh;
    Plane013: THREE.Mesh;
    Plane018: THREE.Mesh;
    Plane018_1: THREE.Mesh;
    Plane018_2: THREE.Mesh;
    Circle001: THREE.Mesh;
    Circle004: THREE.Mesh;
    Circle004_1: THREE.Mesh;
    Circle004_2: THREE.Mesh;
    Plane014: THREE.Mesh;
    Plane015: THREE.Mesh;
    Plane016: THREE.Mesh;
    Circle005: THREE.Mesh;
    Circle005_1: THREE.Mesh;
    Circle005_2: THREE.Mesh;
  };
  materials: {
    ["Material.002"]: THREE.MeshPhysicalMaterial;
    ["Material.003"]: THREE.MeshPhysicalMaterial;
    ["Material.006"]: THREE.MeshStandardMaterial;
    ["Material.007"]: THREE.MeshPhysicalMaterial;
    ["Material.008"]: THREE.MeshPhysicalMaterial;
    ["Material.004"]: THREE.MeshPhysicalMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
    ["Material.011"]: THREE.MeshStandardMaterial;
    ["Material.010"]: THREE.MeshStandardMaterial;
    ["Material.008"]: THREE.MeshPhysicalMaterial;
    ["Material.002"]: THREE.MeshPhysicalMaterial;
    ["Material.003"]: THREE.MeshPhysicalMaterial;
    ["Material.012"]: THREE.MeshStandardMaterial;
    ["Material.014"]: THREE.MeshStandardMaterial;
    ["Material.013"]: THREE.MeshStandardMaterial;
    ["monitor.001"]: THREE.MeshStandardMaterial;
    ["screen.001"]: THREE.MeshStandardMaterial;
    ["monitor 2.001"]: THREE.MeshStandardMaterial;
    ["monitor 2.001"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/program.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[1.26605368, 2.26585865, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_2.geometry}
          material={materials["Material.003"]}
        />
        <group
          position={[-0.6668582, -0.00000892, -0.85025406]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_1.geometry}
            material={materials["Material.006"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_2.geometry}
            material={materials["Material.007"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_3.geometry}
            material={materials["Material.008"]}
          />
        </group>
        <group
          position={[-0.37462127, 0.0068946, -0.54674077]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.91618788}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane001_1.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane001_2.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane001_3.geometry}
            material={materials["Material.006"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002.geometry}
          material={nodes.Plane002.material}
          position={[-0.48812723, 0.0068946, -0.54674077]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.91618788}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003.geometry}
          material={materials["Material.002"]}
          scale={1.02079284}
        />
      </group>
      <group
        position={[-1.41539633, 2.74808693, -0.08592649]}
        rotation={[1.57191613, -Math.PI / 2, 0]}
        scale={0.06135914}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012_1.geometry}
          material={materials["Material.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012_2.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012_3.geometry}
          material={materials["Material.008"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane009.geometry}
        material={materials["Material.002"]}
        position={[-0.76318121, 2.53965473, -0.07275559]}
        rotation={[1.56833414, -1.57053488, 0]}
        scale={[1.07220066, 1.07220066, 1.07220042]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane008.geometry}
        material={materials["Material.011"]}
        position={[1.84845626, 1.19038951, 0.3462598]}
        rotation={[-1.30955029, -1.55742305, -1.30424066]}
        scale={[0.79447567, 0.79447579, 0.7944755]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane005.geometry}
        material={materials["Material.003"]}
        position={[-0.76318121, 2.53965473, -0.07275559]}
        rotation={[1.56833414, -1.57053488, 0]}
        scale={[1.07220066, 1.07220066, 1.07220042]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={materials["Material.012"]}
        position={[1.84746563, 1.19703972, 0.32612911]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.421702, -0.42170218, -0.42170218]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006.geometry}
        material={materials["Material.008"]}
        position={[-1.54652548, 1.51852894, 0.79450589]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.30446699, -0.30446732, -0.30446732]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane007.geometry}
        material={nodes.Plane007.material}
        position={[-1.56221998, 1.61211896, 0.78575319]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.01542854}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012.geometry}
        material={materials["Material.014"]}
        position={[-0.01839611, 3.63952541, 0.55432034]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.35275099}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials["Material.013"]}
        position={[-0.24997042, 3.56578636, 0.54162991]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.34867525}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane013.geometry}
        material={materials["monitor.001"]}
        position={[0.00471771, 0.0389505, 0.44798836]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={1.25554323}
      >
        <group position={[0.05860117, 0.81559151, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane018.geometry}
            material={materials["monitor.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane018_1.geometry}
            material={materials["screen.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane018_2.geometry}
            material={materials["monitor 2.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle001.geometry}
            material={materials["monitor 2.001"]}
            position={[0.02197191, -0.48993027, 0.00256104]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={0.04863328}
          />
        </group>
      </mesh>
      <group
        position={[-1.44727564, 2.95601892, -0.06995709]}
        scale={0.90791482}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle004.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle004_1.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle004_2.geometry}
          material={materials["Material.008"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane014.geometry}
        material={materials["Material.002"]}
        position={[-1.57379341, 0.55565357, 0.87108576]}
        rotation={[1.56833414, -1.57053488, 0]}
        scale={[0.78912234, 0.78912234, 0.78912228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane015.geometry}
        material={materials["Material.003"]}
        position={[-1.57379341, 0.47119606, 0.87108576]}
        rotation={[1.56833414, -1.57053488, 0]}
        scale={[0.78912234, 0.78912234, 0.78912228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane016.geometry}
        material={nodes.Plane016.material}
        position={[-1.67673123, 0.3992573, 0.86168897]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.16846269}
      />
      <group
        position={[-2.09311914, 0.84617364, 0.87213087]}
        scale={0.82710952}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle005.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle005_1.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle005_2.geometry}
          material={materials["Material.008"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/program.glb");
