import '@/styles/globals.scss';
import { Inter, Nunito_Sans } from 'next/font/google';
import NavbarCreatePost from "@/components/Navbar/NavbarCreatePost";
import Navbar from "@/components/Navbar/Navbar";
import { usePathname } from 'next/navigation';
import { SWRConfig } from 'swr';

import 'react-loading-skeleton/dist/skeleton.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname();

  const renderNavbar = () => {
    if (pathname.includes("/dashboard")) {
      return null
    }
    return <Navbar />
  }

  return (
    <SWRConfig value={{ provider: () => new Map() }}>
      <html lang="en">
        <body className={inter.className}>
          <div className="flex flex-col h-screen">
            {renderNavbar()}
            <main className="w-full mx-auto flex-1">
              {children}
            </main>
          </div>
        </body>
      </html>
    </SWRConfig>
  )
}
